# Generated by Django 3.0.3 on 2020-02-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rate',
            new_name='dislike',
        ),
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
