# Generated by Django 3.0.3 on 2020-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20200217_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_picture',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
