# Generated by Django 3.0.3 on 2020-02-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_auto_20200220_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rate',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
