# Generated by Django 3.0.3 on 2020-02-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_auto_20200223_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
